### ISSUE TITLE
Too long command lines

### ISSUE THREAD

**Issue by LockOne** [waugustus/CarpetFuzz#11]
Impressive work :)

I had a problem on replicating the experiment on some subjects,
the generated command lines are too long.

Here's one manpage file example that I had problem : [gm.1](https://drive.google.com/file/d/15d-4j56UTtYnRSTuXd7TYTJDhQ64o1d2/view?usp=sharing)

The generated command line looks like:
```
64
gm animate -adjoin -enhance -help -cycle 8 -wave 30x30 -sampling-factor 2x1 -random-threshold "Intensity 10x30" -rotate "90>" -box "#1f1f1f" -colorspace HWB -loop 8 -map best -metric RMSE -sample 20x20+5+5 -profile -modulate 120,90 -channel -colormap private -colorize 7,21,50 -strokewidth 10 -flop -immutable -mosaic -set "attr 16" -silent -virtual-pixel Constant -shave 1x1 -preserve-timestamp -size 384x256+64 -shadow 20x1 -extent 20x20+5+5 -solarize -pointsize 8 -chop 20x20+5+5 -linewidth -iconic -mode concatenate -encoding AdobeCustom -output-directory -units PixelsPerInch -iconGeometry 20x20+5+5 -morph -scene -average -trim -colors 8 -update 1 -highlight-style -shade 2x1 -verbose -implode 8 -operator "All Multiply 50%" -screen -noise "10|Uniform" -resize 50x30 -snaps 4 -view viewstring -dispose "Background Overwrite the image area with the background color" -window root -dither -compose Minus -ping -compress Fax -affine -spread 4 -backdrop -foreground "#1f1f1f" -version -write /tmp/foo -matte -tile -font PostScript -filter Hamming -displace 50x50 -ordered-dither "Green 3x3" -red-primary 50,30 -equalize -lat 20x20+5 -level 10,1.0,250 -flatten -limit "Width 1920" -raise 50x30 -gravity Center -median 50 -density 50x50 -segment 0.015x1.5 -pen "#efefef01" -emboss 50 -negate -clip -scale 20x20+5+5 -unsharp 0x1.0+1.0+0.05 -maximum-error -resample 30x30 -transparent blue   @@
gm SUB -motion-blur 50x1 -mask -transform -mattecolor "#efefef01" -scenes 0-12 -text-font -file -borderwidth 50 -delay -noop -opaque "#efefef01" -depth 16 -blur 50 -shear -contrast -blue-primary 10,10 -strip -frame -gamma 2.0 -endian Native -define tiff:group-three-options=4 -pause 1 -display -stereo -thumbnail 38x25 -stegano 2 -gaussian 30 -highlight-color "#1f1f1f" -list Type -window-group -roll 50+30 -title "MIFF:bird.miff 512x480" -label "MIFF:bird.miff 512x480" -black-threshold 50%,50%,50%,50% -name -render -hald-clut 8 -recolor "1 0 0, 0 1 0, 0 0 1" -border 50x50 -asc-cdl 1.0,0.0,1.0:1.0,0.0,1.0:1.0,0.0,1.0:1.0 -debug Error -region 20x20+5+5 -despeckle -flip -white-point 30,30 -preview Shade -background "#1f1f1f" -stroke blue -fuzz 50% -auto-orient -interlace Line -coalesce -convolve 20,20 -charcoal 10 -descend -monochrome -quality 2 -watermark 30x30 -white-threshold 50%,50%,50%,50% -log "%u %m:%l %e" -magnify -affine -draw "circle x0,y0 x1,y1" -crop 20x20+5+5 -dissolve 50 -type Grayscale -comment "MIFF:bird.miff 512x480" -normalize -green-primary 30,40 -texture -swirl 10 -repage 20x20+5+5 -paint 10 -treedepth 5 -deconstruct -format ART -process Convert=1,2,3 -threshold 50% -minify 8 -edge 50 -orient undefined -visual StaticColor -intent Relative -append -monitor -remote -use-pixmap -create-directories -fill "#efefef01" -geometry 20x20+5+5 -shared-memory -authenticate password -antialias   @@
...
```
I guess it is not an expected behavior, and I would like to know your opinion.
(I think the number of generated command lines is also low than I expected.)

I changed the order of combination value given to pict execution from 6 (default value) to 4
because my machine (with 128GB RAM) could not handle high combination order values on complex command line manpages (like gm).
Would the decreased value cause the "long command lines" problem?

**Comment by waugustus** [comment]
Thank you very much for your interest in the project. 

Yes, decreasing the value of N in combinatorial testing will reduce the number of generated combinations and prevent excessively long combinations. In our experiments, the number of combinations for `gm` was 916.

To facilitate readers in reproducing the experiment, we will complete the automation of the experiment before June. For processes that require specific resources, such as combinatorial testing, we are considering providing the results directly from that time.

**Comment by LockOne** [comment]
The value seems very high...
May I know the machine spec (RAM size) you used for the experiment?

**Comment by waugustus** [comment]
Hi, I just remembered that due to memory limitations, we didn't actually combine all the options at that time. Instead, we sorted all individual options based on their dry-run coverage and selected the top 50 options with the highest coverage for combination (by modifying the relation file). I will update the code later to automate this process.

**Comment by LockOne** [comment]
Thanks!

**Comment by ahcheongL** [comment]
Do you have a plan to upload the combination used for the experiment?
It is hard to get good results for some big subjects (ex. `gm` and `ffmpeg`) with my 128GB RAM machine.

**Comment by waugustus** [comment]
Yes, see https://github.com/waugustus/CarpetFuzz-experiments

**Comment by ahcheongL** [comment]
I have checked the repository, but it seems the directories are empty.
May I ask where I can find the stub files or combination files?

**Comment by waugustus** [comment]
`configures/*_dataset/argvs` are what you need

**Comment by ahcheongL** [comment]
Ah, sorry to bother you, I had looked at only `carpetfuzz_dataset`.
Thanks.

**Comment by waugustus** [comment]
It's okay, hope this works for you
