### ISSUE TITLE
Manpage problem

### ISSUE THREAD

**Issue by Mist1987** [waugustus/CarpetFuzz#16]
Hi, after installing libtiff, execute the following command:
```
# Step 2
# Use CarpetFuzz to analyze the relationships from the manpage file  ( < 10mins )
python3 ${CarpetFuzz}/scripts/find_relationship.py --file $PWD/build_carpetfuzz/share/man/man1/tiffcp.1
```
The error message "Cannot find /tiffcp.1 file" was displayed. However, I couldn't find the tiffcp.1 file in the installation directory of libtiff (/build_carpetfuzz or /share/man/man1).After copying the /test/manpages/tiffcp.1 file (which was the ONLY .1 file available) to the corresponding directory, the subsequent execution was successful.
So, my question is whether you have written the manpages, such as tiffcp.1, yourself using Groff, or if I just haven't found tiffcp.1 using the correct method?

**Comment by waugustus** [comment]
Hello, and thank you for your interest in CarpetFuzz. I've noticed that starting from libtiff v4.5.0, manpages are **no longer** generated during the compilation process. I'm not aware of the reasons behind this decision by the developers. If you wish to obtain these manpage files, an easy way is to compile **libtiff v4.4.0** once.

**Comment by Mist1987** [comment]
Thanks, you're right. I installed the latest version of libtiff, and it does not include the manpages. Instead, it provides rst files as documentation.

**Comment by Mist1987** [comment]
By the way, I checked the documentation of libtiff today and found out that the developers used Sphinx to write the documentation. So, once Sphinx(need python 3.9+) is installed, we can generate the man .1 file by using the following command:
```
sphinx-build -b man source/rst/dir build/man/dir 
```

**Comment by waugustus** [comment]
Thank you very much for your reminder. I will include this command in the README.
