### ISSUE TITLE
Cannot run the fuzzer with steps in README

### ISSUE THREAD

**Issue by 13579and2468** [waugustus/CarpetFuzz#6]
I use [tiffcp.1](https://github.com/waugustus/CarpetFuzz/blob/main/tests/manpages/tiffcp.1) which you provided and step by step as README.

I generated relation_tiffcp.json and combination_tiffcp.txt as appended files in generated_file.zip.

It always get zero coverage when I do Step 3 to fuzz tiffcp
![Selection_271](https://user-images.githubusercontent.com/71592529/233839756-126a7bbc-ebec-4667-aebc-a4d6287b71e1.png)

[generated_file.zip](https://github.com/waugustus/CarpetFuzz/files/11303707/generated_file.zip)

Thanks

**Comment by 13579and2468** [comment]
provid initial seed fuzzer use : [input.zip](https://github.com/waugustus/CarpetFuzz/files/11303744/input.zip)

**Comment by waugustus** [comment]
Hi, could you please provide me with the command you used to test the program and the version of LLVM you're using? I tested it myself and the fuzzer worked well. After comparing the contents of the 'generated_file.zip' you provided and the ones I generated locally, I found no differences, so I think the issue may be related to the version of LLVM.

```
# Command
${CarpetFuzz}/fuzzer/afl-fuzz -i input/ -o output/ -K ${CarpetFuzz}/output/stubs/ranked_stubs_tiffcp.txt -- $PWD/build_carpetfuzz/bin/tiffcp @@

# clang --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by 13579and2468** [comment]
# Command
${CarpetFuzz}/fuzzer/afl-fuzz -i input/ -o output/ -K ${CarpetFuzz}/output/stubs/ranked_stubs_tiffcp.txt -- $PWD/build_carpetfuzz/bin/tiffcp @@

#  clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by 13579and2468** [comment]
After I re-compile the fuzzer with LLVM_CONFIG=llvm-config-12 and re-compile libtiff, it can get coverage now.

Thanks

**Comment by waugustus** [comment]
It's great to hear that.
